# Generated by Django 3.2.7 on 2022-01-03 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_move_tags_to_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='product.product'),
        ),
    ]
