# Generated by Django 3.2.7 on 2022-01-06 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_add_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='preview',
        ),
        migrations.AddField(
            model_name='image',
            name='position_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='extend_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extend_product', to='product.image'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_product', to='product.image'),
        ),
        migrations.AddField(
            model_name='product',
            name='mobile_main_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_main_product', to='product.image'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumb_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumb_product', to='product.image'),
        ),
    ]
