# Generated by Django 3.2.7 on 2022-01-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_add_image_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='texture_size',
            field=models.CharField(max_length=20),
        ),
    ]
