# Generated by Django 3.2.7 on 2022-01-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_change_texture_size_to_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='texture_size',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
