# Generated by Django 3.2.7 on 2022-01-11 08:04

import apps.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('product', '0008_change_allow_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=apps.product.models.get_directory_path),
        ),
        migrations.AlterField(
            model_name='model',
            name='file',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='category.Tag'),
        ),
    ]
