# Generated by Django 3.2.7 on 2022-01-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_set_default_storage_to_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_size',
            field=models.IntegerField(default=0),
        ),
    ]
