# Generated by Django 3.2.7 on 2021-12-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nick_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
