# Generated by Django 3.2.7 on 2022-01-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_add_user_admin_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
