# Generated by Django 3.2.7 on 2022-02-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_add_user_product_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_mail_sent',
            field=models.DateTimeField(null=True),
        ),
    ]
