# Generated by Django 3.2.7 on 2022-03-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_reset_mail_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
