# Generated by Django 3.2.7 on 2021-12-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_add_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewebpayResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=10)),
                ('MerchantID', models.CharField(max_length=20)),
                ('TradeInfo', models.TextField()),
                ('TradeSha', models.TextField()),
                ('Version', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='newebpaypayment',
            name='json',
        ),
    ]
