# Generated by Django 3.2.7 on 2021-12-21 05:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_add_newebpayresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='newebpayresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_by',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_trans_no', models.CharField(max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('invoice_number', models.CharField(max_length=10)),
                ('random_num', models.CharField(max_length=4)),
                ('check_code', models.CharField(max_length=64)),
                ('barcode', models.CharField(max_length=50)),
                ('qrcode_l', models.CharField(max_length=200)),
                ('qrcode_r', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='order.order', related_name="invoice")),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='order.newebpaypayment', related_name="invoice")),
            ],
        ),
    ]
