# Generated by Django 3.2.7 on 2021-12-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_add_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_count',
            field=models.IntegerField(default=0),
        ),
    ]
