# Generated by Django 3.2.7 on 2022-01-14 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_add_order_success_payment_and_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='newebpaypayment',
            name='encrypted_data',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='decrypted_payment', to='order.newebpayresponse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newebpayresponse',
            name='is_decrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newebpayresponse',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='newebpay_responses', to='order.order'),
        ),
        migrations.AlterField(
            model_name='newebpaypayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='newebpay_payments', to='order.order'),
        ),
    ]
