# Generated by Django 3.2.7 on 2022-01-14 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_add_payment_order_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newebpaypayment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='newebpay_payments', to='order.order'),
        ),
    ]
