# Generated by Django 3.2.7 on 2022-01-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_add_invoice_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_merchant_order_no',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_counter',
            field=models.IntegerField(default=1),
        ),
    ]
