# Generated by Django 3.2.7 on 2022-05-31 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_newebpaypayment_encrypted_data'),
    ]

    operations = [
        migrations.RenameModel('Invoice', 'EInvoice'),
    ]
