# Generated by Django 3.2.7 on 2022-05-31 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_rename_invoice_to_einvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=10, null=True)),
                ('real_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_address', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('tax_number', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='einvoice',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='e_invoice',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='order.einvoice'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='einvoice',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='e_invoice', to='order.newebpaypayment'),
        ),
        migrations.AddField(
            model_name='order',
            name='paper_invoice',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='order.paperinvoice'),
        ),
    ]
