# Generated by Django 3.2.7 on 2022-05-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_invoice_to_paper_and_elec'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperinvoice',
            name='type',
            field=models.IntegerField(default=2),
        ),
    ]
