# Generated by Django 3.2.7 on 2023-02-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_add_paper_invoice_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('currency', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        )
    ]
