# Generated by Django 3.2.7 on 2022-05-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='langconfig',
            name='text_nickname',
        ),
        migrations.AddField(
            model_name='langconfig',
            name='btn_next',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='langconfig',
            name='cart_invoice_company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='langconfig',
            name='cart_invoice_tax_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='langconfig',
            name='cart_invoice_text_re_fill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='langconfig',
            name='cart_invoice_text_same_as',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='langconfig',
            name='cart_invoice_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='langconfig',
            name='cart_invoice_type_electronic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='langconfig',
            name='cart_invoice_type_paper',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='langconfig',
            name='cart_invoice_way_duplicate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='langconfig',
            name='cart_invoice_way_triplicate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='langconfig',
            name='cart_member_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='langconfig',
            name='cart_member_info_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='langconfig',
            name='cart_member_real_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='langconfig',
            name='cart_text_fill_out_message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='langconfig',
            name='cart_text_fill_out_warning',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
