# Generated by Django 3.2.7 on 2022-06-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0002_update_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='langconfig',
            name='member_no_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
