# Generated by Django 3.2.7 on 2022-01-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_add_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(null=True, upload_to='index/about_us'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='image',
            field=models.ImageField(null=True, upload_to='index/tutorials'),
        ),
    ]
