# Generated by Django 3.2.7 on 2022-01-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_set_default_storage_to_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='product',
        ),
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(null=True, upload_to='static-storage/index/banners'),
        ),
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(null=True, upload_to='static-storage/index/about_us'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='image',
            field=models.ImageField(null=True, upload_to='static-storage/index/tutorials'),
        ),
    ]
