# Generated by Django 3.2.7 on 2022-02-08 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_add_privacy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='description',
            new_name='detail',
        ),
    ]
