# Generated by Django 3.2.7 on 2022-03-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_rename_banner_description_to_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='detail',
            new_name='description',
        ),
        migrations.AddField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(null=True, upload_to='static-storage/index/banners'),
        ),
    ]
